混淆后把源代码删除，再加上commit用随机的

diff --git a/.github/workflows/Obfuscate.yml b/.github/workflows/Obfuscate.yml
--- a/.github/workflows/Obfuscate.yml
+++ b/.github/workflows/Obfuscate.yml
@@ -5,8 +5,8 @@ on:
     branches:
       - main
   schedule:
-        # Runs everyday at 1:00 AM
-        - cron: "0 1 * * *"
+    # Runs everyday at 1:00 AM
+    - cron: "0 1 * * *"
 
 permissions:
   contents: write
@@ -26,12 +26,16 @@ jobs:
 
       - name: Install dependencies
         run: |
-          npm install -g javascript-obfuscator          
+          npm install -g javascript-obfuscator
 
-      - name: Clone BPB workjs
+      - name: Download BPB worker js
         run: |
-          wget -O origin.js https://raw.githubusercontent.com/bia-pain-bache/BPB-Worker-Panel/refs/heads/main/build/unobfuscated-worker.js          
-      
+          wget -O origin.js https://raw.githubusercontent.com/bia-pain-bache/BPB-Worker-Panel/refs/heads/main/build/unobfuscated-worker.js
+          if [ $? -ne 0 ]; then
+            echo "Failed to download origin.js"
+            exit 1
+          fi
+
       - name: Obfuscate BPB worker js
         run: |
           javascript-obfuscator origin.js --output _worker.js \
@@ -46,12 +50,30 @@ jobs:
           --string-array-encoding 'rc4' \
           --string-array-threshold 1 \
           --transform-object-keys true \
-          --unicode-escape-sequence true          
+          --unicode-escape-sequence true
+          if [ $? -ne 0 ]; then
+            echo "Obfuscation failed"
+            exit 1
+          fi
+
+      - name: Remove original file
+        run: rm origin.js
+
+      - name: Generate random commit message
+        id: commit_message
+        run: echo "::set-output name=message::$(cat /dev/urandom | tr -dc A-Za-z0-9\  | head -c 60)"
+
+      - name: Check for changes
+        id: check_changes
+        run: |
+          git add _worker.js
+          git diff --cached --quiet || echo "::set-output name=has_changes::true"
 
       - name: Commit changes
+        if: steps.check_changes.outputs.has_changes == 'true'
         uses: stefanzweifel/git-auto-commit-action@v5
         with:
           branch: main
-          commit_message: ':arrow_up: update latest bpb panel'
+          commit_message: "${{ steps.commit_message.outputs.message }}"
           commit_author: 'github-actions[bot] <github-actions[bot]@users.noreply.github.com>'
           push_options: '--set-upstream'
